services:
  postgres-user:
    image: postgres:latest
    container_name: postgres_container_userdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: axelia
      POSTGRES_DB: userdb
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data_userdb

  postgres-notebook:
    image: postgres:latest
    container_name: postgres_container_notebookdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: axelia
      POSTGRES_DB: notebookdb
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data_notebookdb

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data:
